# DAY 2

## INTRODUCTION TO R MARKDOWN (EDWARDS)

Edwards presented an intro to the basics of R markdown. R markdown allows us to interspace text, R code, and R output. This is then elegantly converted into html, pdf, or word formats using the knitr package and pandoc (a universal document converter). Markdown is compatible with latex, but is a much simpler to learn markup language. Basic formatting options were presented.
Some recommendations included naming our code chunks using unique and useful descriptions (aids in using caches and finding errors) and that caches are useful when working with large datasets.

## INTRODUCTION TO **csasdown** (ANDERSON)

Pacific region has written an R package called csasdown  (based on bookdown R package) to help authors write research documents formatted for Canadian Science Advisory Secretariat.  

After loading csasdown a template document can be produced using the following R code:

```{r create-draft-csas-doc, eval=FALSE, echo=TRUE}
library(csasdown)
rmarkdown::draft("index.Rmd", template = "resdoc", package = "csasdown", create_dir = FALSE, edit = FALSE)
```


Using this draft document, we explored how to produce and link figures, tables, and references within a research document.


## OPEN DATA PROTOCOLS (BRUCE PATTEN)

Bruce Patten, section head of the Fisheries and Assessment Data Unit, talked about data standards. He described Darwin Core, a model for “observational” data that has terms and definitions that facilitate the exchange of information about the geographic occurrence of organisms, and how it may be applied to fisheries survey data. He listed several online repositories for biological data that use Darwin Core data standards including [Ocean Biogeographic Information Systes: http://www.iobis.org](http://www.iobis.org) and related R tools (RODBC, robis and obistools R packages).


## DEFENSIBLE SCIENCE ADVICE (KRONLUND)










