# DAY 1

## MOTIVATION FOR THE WORKSHOP (EDWARDS AND DUPLISEA)

This workshop was motivated by several recent developments:

(1) The TESA Template Model Builder (TMB) course in Halifax in January 2018
introduced many DFO assessment scientists to tools such as GitHub and the
advantages of a strong versioning system, centralised methods repositories, and
the ability to share code. Git and GitHub were already well used at the Pacific
Biological Station but not so much in other DFO labs, and the national
advantages of this became clearer after the TMB course.

(2) The International Council for the Exploration of the Sea (ICES)
has developed an initiative called the [Transparent Assessment
Framework (TAF)](https://github.com/ices-taf) that works towards TTT goals.
ICES representatives gave a webinar to TESA in the Spring of 2017 on this
initiative, which was a source of inspiration in developing this TTT workshop.

(3) There has been a desire in DFO to create a common look and feel in DFO
science advice in assessment. Previous experience has shown that this does not
work well when pushed from the top down, but use of these modern sharing tools
should help create some common looking outputs as emergent products of this way
of working.

(4) [Bill C-68](http://www.parl.ca/DocumentViewer/en/42-1/bill/C-68/third-reading)
(changes to the Fisheries Act) is
currently in the Senate. Bill C-68 contains specific wording around the need to
develop limit reference points and recovery plans. The legislated need for
these products that come from assessment scientists' workbenches is a motivating
factor to work clearly in a TTT framework.

(5) The need to develop bilingual documentation for DFO CSAS documents
motivates the
development of translation tools for tables and graphics that can be done
consistently, relatively instantly, and across all regions. The fourth and
appropriately silent T in TTT can be considered translation, but in reality
Translation is no less important than the others.

## ADVANTAGES OF USING A TTT APPROACH

Assessment staff work collaboratively and previous methods for collaboration
(e.g., email) are inefficient and prone to errors while a structured sharing
system with versioning and update notifications is much more efficient.
Assessment models generally need to be updated every time a new assessment is
scheduled, rather than built from the ground up, but the technical team
running the model may change from year to year. Transferable approaches allow a 
more efficient transfer of code to new staff to get them up and running. Otherwise,
substantial amounts of work are likely to be unnecessarily repeated --- repetition
is avoided when
code (including the writing up of lengthy assessment documents) 
is easily transferable among individuals and constructed in a
transparent manner.

## MOTIVATION FOR USING Git (EDWARDS)

Emailing individual files between an assessment team does not preserve folder structure, which is important
for code functionality, particularly when building complicated models with
nested functions. Using Git and GitHub is more efficient and less prone to errors by
preserving folder structure and allows analysts to work on code simultaneously.

Git tracks changes to files and keeps all previous changes, so that
previous versions are never lost. GitHub is a web-based service for sharing and
collaborating on code. By using branches, individual developers can
simultaneously work on the same project without worrying about overwriting each
others' work. Git merges versions of the document edited by different users, and
highlights lines with conflicts that need to be resolved. Git also tracks who
made which changes, which can be viewed using the `blame` button. During
development (or post-development), Git also allows analysts to easily reference
pieces of code and/or changes in code easily when posing questions or issues,
using remote repositories. Issues can be easily tracked on the GitHub site and
used as a continuously updated to-do list, with a permanently recorded history.
Individual issues that need to be addressed can also be assigned to specific
analysts within a working group.


## INTERACTIVE INTRODUCTION TO Git (EDWARDS AND GRANDIN)

Chris Grandin and Andrew Edwards led the group though the steps for basic Git 
functions:

- creating a remote repository on a host site (e.g., GitHub)
 - also included adding a `.gitignore` file that specifies files that Git should not track (e.g., data files)
- cloning the repository to your local hard drive
- adding a file to the repository
- staging and committing the file with an informative message
- editing files
- staging and committing changes to update the document
- pushing to the remote repository and
- referencing previous commits using their `HASH` code.

A `.gitconfig` file was shared that includes useful keyboard shortcuts.

Next Andrew addressed a family of Git functions that are more likely to be used
during a collaboration:

- making a new branch separate from the master
- merging branches, and addressing any conflicts that arise
- pushing branches upstream so they can be accessed by others
- deleting old branches to keep your workspace tidy
- stashing changes that have not been committed when you switch branches
- examining network graphs (on GitHub site) to interpret branch structure
- adding remote forks and fetching a collaborator's changes from them
- use `git diff` to compare changes between a collaborator's branch or fork and 
yours.
