# DAY 2

## INTRODUCTION TO R Markdown (EDWARDS)

Andrew Edwards presented an intro to the basics of R Markdown.  R Markdown
allows analysts to intersperse text, R code, and R output.  This is then
elegantly converted into HTML, PDF, or Word formats using the knitr and
rmarkdown R packages and pandoc (a universal document converter).  R Markdown is
a markup language that is compatible with LaTeX, but much simpler to learn.
Basic formatting options were presented.  Some recommendations included naming
code chunks using unique and useful descriptions (to aid in using caches and
finding errors), and that caches are useful when working with large data sets.

## INTRODUCTION TO csasdown (ANDERSON)

Pacific Region has written an R package called csasdown (based on the R packages
bookdown and thesisdown) to help authors write Research Documents formatted for
the Canadian Science Advisory Secretariat
[(CSAS)](http://www.dfo-mpo.gc.ca/csas-sccs/index-eng.htm).

A template document can be produced using the following R code:

```{r create-draft-csas-doc, eval=FALSE, echo=TRUE}
# devtools::install_github("pbs-assess/csasdown")
library(csasdown)
rmarkdown::draft("index.Rmd", template = "resdoc", package = "csasdown",
  create_dir = FALSE, edit = FALSE)
```

Using this draft document, we explored how to produce and link figures, tables,
and references within a Research Document.

## OPEN DATA PROTOCOLS (BRUCE PATTEN)

Patten presented an overview of the Darwin Core (DWC) observational data model,
and the benefits of its potential application to fisheries science.  This data
model provides a standard for representing survey data in a consistent format
that allows for integration of data sets from multiple sources.  The DWC model
has been extended by the [Ocean Biogeographic Information System
(OBIS)](http://www.iobis.org) initiative to be more useful for marine biological
and oceanographic survey data and is called the OBIS-ENV-DATA schema.  He listed
several online repositories for biological data that use Darwin Core data
standards including OBIS and related R tools (RODBC, robis, and obistools R
packages).  Several international data sharing initiatives such as OBIS are
exchanging data using this format.  Canada has committed to contributing to
these efforts, and DFO has already participated to some degree.  There are some
R packages available that provide the user with tools for interacting with data
in the OBIS format of DWC.  Mr. Patten proposes that DFO Science put some effort
towards mapping existing databases to the OBIS-ENV-DATA schema with the idea of
developing data sets in this format for use by analysts.

## DEFENSIBLE SCIENCE ADVICE (KRONLUND)

Kronlund provided a brief overview of the broad implications of Bill C-68 in the
context of the DFO PA Framework [@DFO2013].  Proposed language in [Bill
C-68](http://www.parl.ca/DocumentViewer/en/42-1/bill/C-68/third-reading) implies
there will be legislative imperatives for evidence to support management
measures to maintain stocks at or above sustainable levels (Provision 6.1(1)),
maintain stocks above the Limit Reference Point (Provision 6.1(2)), and rebuild
stocks above the Limit Reference Point in the provided time periods (Provision
6.2).  The provisions require taking into account the biology of the fish and
environmental conditions affecting the stock.  Fish stocks currently tracked by
the [Sustainability Survey for
Fisheries](http://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/survey-sondage/index-en.html),
and others as needed, will need PA Framework elements to meet requirements under
Bill C-68 (i.e., reference points, harvest control rules, consideration of
uncertainty).  In general, defending science advice means the advice meets
current standards of acceptable scientific and fisheries management practice,
including reproducible science, a key element of this workshop.  The suite of
software tools discussed in the workshop also enables national standardization
of how uncertainty, stock status, and risks associated with management
trade-offs are communicated, a step that would also improve the defence of
science advice.
