# DAY 3

## WRITING R PACKAGES (ANDERSON)

The third day of the TTT workshop started with a presentation by Sean Anderson on R package development.
Sean used materials from presentations by Hadley Wickam (senior scientist at RStudio) to get participants started with developing R packages.
The development of R packages is greatly simplified by using an RStudio project, and taking advantage of its many available tools related to package development.
For example, one can create a project in RStudio and define it as an R package, and the software will create the necessary backbone of an R package.
Sean covered the development of an R package, the generation of its documentation using roxygen2, unit testing of the package, and package testing.

Participants did exercises to learn how to alter an example package.
Sean demonstrated how to create a new file in an R package environment employing the `usethis::use_r("file-name")` function.
He also provided tips on how to edit the users R profile to load key packages.
Sean presented resources from Hadley Wickham such as "Advanced R" [@Wickham2014], "R Packages" [@Wickham2015] and "R for Data Science" [@Wickham2017].
These resources are available on line as well as in print form.

## TRANSLATING CSAS DOCUMENTS (ANN MARISCAK)

Ann presented on the new policies for generating CSAS documents.
As a legal requirement, the Department must ensure that all CSAS documents are written into both official languages.
As well, it is required that the documents be accessible for persons with disabilities and be compatible with tools such as screen readers.
It was noted that translation of text will slow the final output of documents and increase their cost.
Tools such as latex and csasdown may be able to assist in translation, and thereby shorten the time and reduce the cost to produce fully translated documents.
Another problem is translation of figures (which are png 'images' in pdf documents) into the other official language.
It was suggested that it might be possible for an automated translation of frequently used words such as "Age" or "Fork length".

### Editing vs. translation

There was a suggestion that documents can be translated to French using Google Docs, and then sent for 'editing' as opposed to 'translation.'
If editing is less a less expensive service than translation, this could be an option worth considering in some situations.
Authors choosing to do this would have to ensure the integrity of the text was correctly maintained through the translation process.

### Translation databases

Ann mentioned the existence of a Government of Canada database called [Termimum Plus](https://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng).
Termimum Plus is an invaluable tool used for the translation of technical terminology.
The quality of the translation are perpetually being improved through expert-user feedback and contribution.
Daniel Ricard made mention of another translation database native to DFO called the [DFO Bilingual Lexicon](http://www.btb.termiumplus.gc.ca/).

## BREAK-OUT GROUPS

Workshop participants separated out into five break-out groups.
Workshop participants were able to self-select which group they went to, which worked well.

The first of these groups worked on an applied example, in which they worked together to compose a trip report for a the Newfoundland and Labrador Region using R Markdown.

The second of these groups focused on a brainstorming session about the development of tools to automate language translation of figures in CSAS documents.
This resulted in the creation of a new R package [rosettafish](https://github.com/pbs-assess/rosettafish), which translates common figure annotations between English, French, and Inuktitut.

The remaining three groups worked on collaboratively writing text for this workshop proceedings document using GitHub, with each group tasked with summarizing one day of the workshop.
A proceedings template document that met the format requirements for a `Canadian Technical Report of Fisheries and Aquatic Sciences' was compiled ahead of time.
The three report-writing groups were able to clone the relevant repository and make changes to the template.

### Multi-species survey automated report

A breakout group (Krista Baker, Brendan Connors, Kevin Hedges, Bob Roger, Mark
Simpson, and Laura Wheeland) was formed to work on an applied example of all of
the workshop topics.
The group created a GitHub repository, an R project, and an R Markdown document to standardize and automate the creation of RV survey trip reports.
The group used the Newfoundland and Labrador Region multispecies surveys as a test case, and tailored the project to handling the particular data structure from those surveys, but the project could easily be adapted for other trip types (e.g., Shellfish surveys).
Work was divided among group members, and coordinated through GitHub.
Individual tasks included creating the GitHub repository, creating the R project, drafting separate R Markdown files to provide a trip summary, survey map, and catch summary, and then creating a bookdown file to combine the separate R Markdown files into a single pdf report.
The R Markdown files combined standard text and dynamic calculations in R to automatically generate survey details and summary results.
By the end of the workshop the report project was completed, and automated survey reports had been successfully generated.
