# DAY 4

## Git FOR GOVERNMENT OF CANADA EMPLOYEES (RICARD)

The Government of Canada, through Shared Services Canada, has a GitLab
enterprise account called [gccode](https://gccode.ssc-spc.gc.ca "gccode
homepage").  One must be on the DFO network (or any Government of Canada
network) to access the website and the remote Git server.  DFO employees can
create an account on gccode, and use it in the same way that they would use
GitHub.  One advantage of using gccode is that it is provided by Shared Services
Canada and therefore has no privacy concerns that may arise from using a
publicly available system such as GitHub (although GitHub does provide private
repositories, and GitHub is not used to share data).
The downside is that the Git server
can only be access from your office or from a VPN (Virtual Private Network), and
thus
cannot be used for collaboration with non-government colleagues.

## BREAK-OUT GROUPS

Workshop participants continued to work in small groups on tasks from the
previous day, including writing this report. The rosettafish R package continued
to be developed and will be used for translating >200 full pages of 
figures in 'A reproducible data synopsis for over 100 species of British
Columbia groundfish', a CSAS Working Paper that will be revised and finalised as
a Research Document in 2019.
